//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : BookingList.java
//  @ Date : 17/03/2016
//  @ Author : 
//
//




public class BookingList {
	private BookingFactory bookingList;
	public BookingFactory removeBooking(bookingRef ref) {
	
	}
	
	public BookingFactory) editBooking(bookingRef ref) {
	
	}
	
	public BookingFactory findBooking(bookingRef ref) {
	
	}
}
