//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : BookingFactoryPatternDemo.java
//  @ Date : 17/03/2016
//  @ Author : 
//
//




public class BookingFactoryPatternDemo {
	public void main() {
	
	}
}
