//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : BookingDataBase.java
//  @ Date : 17/03/2016
//  @ Author : 
//
//




public class BookingDataBase {
	public void update() {
	
	}
	
	public void store() {
	
	}
}
