//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : CustomerUI.java
//  @ Date : 17/03/2016
//  @ Author : 
//
//




public class CustomerUI {
	private EditBookingController control;
	public void displayResults() {
	
	}
	
	public char selectBooking() {
	
	}
}
