//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DeleteBooking.java
//  @ Date : 17/03/2016
//  @ Author : 
//
//




public class DeleteBooking {
	private BookingList list;
	public void deleteBooking(BookingList; ref: bookingRef list) {
	
	}
}
