//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MemberType.java
//  @ Date : 17/03/2016
//  @ Author : 
//
//




public class MemberType {
	public void getType() {
	
	}
}
