//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Member.java
//  @ Date : 17/03/2016
//  @ Author : 
//
//




public class Member extends MemberType, MemberType {
	public void getType() {
	
	}
}
