//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ViewBooking.java
//  @ Date : 17/03/2016
//  @ Author : 
//
//




public class ViewBooking {
	private BookingList list;
	public void viewBooking(BookingList;ref:bookingRef list) {
	
	}
}
