//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : BookingFactory.java
//  @ Date : 16/03/2016
//  @ Author : 
//
//




public class BookingFactory {
	private String bookingRef;
	private String customerName;
	private Date bookingDate;
	private Clock24 bookingTime;
	private Integer numberOfSeats;
	private Journey journey;
	public Journey GiveJourneyDetails;
	public String getCustomerName() {
	
	}
	
	public Date getDate() {
	
	}
	
	public Clock24 getTime() {
	
	}
	
	public Integer getNumberOfSeats() {
	
	}
	
	public Boolean updateBooking() {
	
	}
	
	public void viewbooking() {
	
	}
	
	public void remove(bookingRef ref) {
	
	}
	
	public void amend(bookingRef ref) {
	
	}
	
	public MemberType getType() {
	
	}
}
