//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DeletBooking.java
//  @ Date : 16/03/2016
//  @ Author : 
//
//




public class DeletBooking {
	private BookingList list;
	public void deleteBooking(BookingList; ref: bookingRef list) {
	
	}
}
