//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : EditBooking.java
//  @ Date : 16/03/2016
//  @ Author : 
//
//




public class EditBooking {
	private BookingList list;
	public void editBooking(BookingList; ref:bookingRef list) {
	
	}
}
