//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FactoryProducer.java
//  @ Date : 16/03/2016
//  @ Author : 
//
//




public class FactoryProducer {
	public BookingFactory getFactory() {
	
	}
}
