//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Journey.java
//  @ Date : 16/03/2016
//  @ Author : 
//
//




public class Journey {
	private String journeyName;
	private String journeyLocation;
	private Date journeyDate;
	public BookingFactory CheckJourneyDetails;
	public String getJourneyName() {
	
	}
	
	public String getJourneyLocation() {
	
	}
	
	public Date getJourneyDate() {
	
	}
	
	public void setJourneyName(String aName) {
	
	}
	
	public void setJourneyLocation(String aLocation) {
	
	}
	
	public void setJourneyDate(Date aDate) {
	
	}
}
