//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MemberType.java
//  @ Date : 16/03/2016
//  @ Author : 
//
//




public interface MemberType {
	public void display()();
}
