//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Member.java
//  @ Date : 16/03/2016
//  @ Author : 
//
//




public class Member extends TypeFactory, MemberType {
	public void get() {
	
	}
}
