//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : TypeFactory.java
//  @ Date : 16/03/2016
//  @ Author : 
//
//




public class TypeFactory extends BookingFactory, BookingFactory {
	public MemberType getType() {
	
	}
}
