
import javax.swing.JOptionPane;

//import required libraries for communicating with the sql database
import java.sql.*;
import javax.swing.*;
import java.util.*;
import java.awt.*;

//import library for random variable
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/*SQL statements tutorial: https://www.youtube.com/watch?v=yJqAqgbcgnU*/

/**
 *
 * @author A
 */
public class OperatorGUI extends javax.swing.JFrame {

    /**
     * Creates new form OperatorGUI
     */
    public OperatorGUI() {
        initComponents();
        BookaTripFrame.setVisible(false);
        EditBookingButton.setEnabled(false);
        DeleteBookingButton.setEnabled(false);
        EditTripFrame.setVisible(false);
        BookingInfoFrame.setVisible(false);
        BookingReportFrame.setVisible(false);
        RegisterMemberFrame.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BookingInfoFrame1 = new javax.swing.JInternalFrame();
        MakeBookingPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        BookingIDField = new javax.swing.JTextField();
        VerifyBookingButton = new javax.swing.JButton();
        BookATripButton = new javax.swing.JButton();
        EditBookingButton = new javax.swing.JButton();
        ViewBookingReport = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        BookaTripFrame = new javax.swing.JInternalFrame();
        MakeBookingPanel = new javax.swing.JPanel();
        ConfirmBookingButton = new javax.swing.JButton();
        DepartureBox = new javax.swing.JComboBox<>();
        DestinationBox = new javax.swing.JComboBox<>();
        DayBox = new javax.swing.JComboBox<>();
        MonthBox = new javax.swing.JComboBox<>();
        YearBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        MemberBox = new javax.swing.JCheckBox();
        NonMemberBox = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        EditTripFrame = new javax.swing.JInternalFrame();
        MakeBookingPanel1 = new javax.swing.JPanel();
        ConfirmBookingButton1 = new javax.swing.JButton();
        DepartureBox1 = new javax.swing.JComboBox<>();
        DestinationBox1 = new javax.swing.JComboBox<>();
        DayBox1 = new javax.swing.JComboBox<>();
        MonthBox1 = new javax.swing.JComboBox<>();
        YearBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        MemberBox1 = new javax.swing.JCheckBox();
        NonMemberBox1 = new javax.swing.JCheckBox();
        DeleteBookingButton = new javax.swing.JButton();
        BookingInfoFrame = new javax.swing.JInternalFrame();
        MakeBookingPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        BookingReportFrame = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        BookingReportTable = new javax.swing.JTable();
        DayBox3 = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        MonthBox3 = new javax.swing.JComboBox<>();
        YearBox3 = new javax.swing.JComboBox<>();
        WeeklyReportBtn = new javax.swing.JButton();
        MonthlyReportBtn = new javax.swing.JButton();
        RegisterMemberFrame = new javax.swing.JInternalFrame();
        MakeBookingPanel4 = new javax.swing.JPanel();
        ConfirmBookingButton2 = new javax.swing.JButton();
        DayBox2 = new javax.swing.JComboBox<>();
        MonthBox2 = new javax.swing.JComboBox<>();
        YearBox2 = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        NameTextBox = new javax.swing.JTextField();
        EmailTextBox = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        ContactNumberTextBox = new javax.swing.JTextField();

        BookingInfoFrame1.setClosable(true);
        BookingInfoFrame1.setResizable(true);
        BookingInfoFrame1.setTitle("Booking Information");
        BookingInfoFrame1.setEnabled(false);
        BookingInfoFrame1.setVisible(true);

        jLabel15.setText("Date:");

        jLabel16.setText("Destination:");

        jLabel17.setText("Departure:");

        jLabel18.setText("Payment:");

        jLabel19.setText("jLabel11");

        jLabel20.setText("jLabel12");

        jLabel21.setText("jLabel13");

        jLabel22.setText("jLabel14");

        javax.swing.GroupLayout MakeBookingPanel3Layout = new javax.swing.GroupLayout(MakeBookingPanel3);
        MakeBookingPanel3.setLayout(MakeBookingPanel3Layout);
        MakeBookingPanel3Layout.setHorizontalGroup(
            MakeBookingPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MakeBookingPanel3Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(MakeBookingPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MakeBookingPanel3Layout.createSequentialGroup()
                        .addGroup(MakeBookingPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(MakeBookingPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20))
                        .addGap(5, 5, 5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MakeBookingPanel3Layout.createSequentialGroup()
                        .addGroup(MakeBookingPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MakeBookingPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel21))))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        MakeBookingPanel3Layout.setVerticalGroup(
            MakeBookingPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MakeBookingPanel3Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(MakeBookingPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(MakeBookingPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addGroup(MakeBookingPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MakeBookingPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jLabel18))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout BookingInfoFrame1Layout = new javax.swing.GroupLayout(BookingInfoFrame1.getContentPane());
        BookingInfoFrame1.getContentPane().setLayout(BookingInfoFrame1Layout);
        BookingInfoFrame1Layout.setHorizontalGroup(
            BookingInfoFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookingInfoFrame1Layout.createSequentialGroup()
                .addComponent(MakeBookingPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        BookingInfoFrame1Layout.setVerticalGroup(
            BookingInfoFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookingInfoFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MakeBookingPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        BookingIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookingIDFieldActionPerformed(evt);
            }
        });
        BookingIDField.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                BookingIDFieldInputMethodTextChanged(evt);
            }
        });

        VerifyBookingButton.setText("Verify Booking");
        VerifyBookingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerifyBookingButtonActionPerformed(evt);
            }
        });

        BookATripButton.setText("Book a Trip");
        BookATripButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookATripButtonActionPerformed(evt);
            }
        });

        EditBookingButton.setText("Edit Booking");
        EditBookingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditBookingButtonActionPerformed(evt);
            }
        });

        ViewBookingReport.setText("View Booking Report");
        ViewBookingReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewBookingReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(BookingIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(VerifyBookingButton)
                .addGap(22, 22, 22))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BookATripButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EditBookingButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ViewBookingReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BookingIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VerifyBookingButton))
                .addGap(27, 27, 27)
                .addComponent(BookATripButton)
                .addGap(18, 18, 18)
                .addComponent(EditBookingButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ViewBookingReport)
                .addContainerGap(945, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Booking", jPanel2);

        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jButton1)
                .addContainerGap(124, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jButton1)
                .addContainerGap(1072, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Customer", jPanel3);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        BookaTripFrame.setClosable(true);
        BookaTripFrame.setTitle("Book a Trip");
        BookaTripFrame.setEnabled(false);
        BookaTripFrame.setVisible(true);

        ConfirmBookingButton.setText("Confirm Booking");
        ConfirmBookingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmBookingButtonActionPerformed(evt);
            }
        });

        DepartureBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Coventry", "London", "Luton", "Milton Keynes", "Cardiff", "Northhampton", " " }));
        DepartureBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepartureBoxActionPerformed(evt);
            }
        });

        DestinationBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "London", "Luton", "Milton Keynes", "Cardiff", "Northhampton", "Coventry" }));
        DestinationBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DestinationBoxActionPerformed(evt);
            }
        });

        DayBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        DayBox.setToolTipText("Day");

        MonthBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        MonthBox.setToolTipText("Month");

        YearBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2016", "2017", "2018", "2019", "2020" }));
        YearBox.setToolTipText("Year");

        jLabel1.setText("Date:");

        jLabel2.setText("Destination:");

        jLabel3.setText("Departure:");

        MemberBox.setText("Member (£20)");
        MemberBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MemberBoxActionPerformed(evt);
            }
        });

        NonMemberBox.setSelected(true);
        NonMemberBox.setText("Non-Member (£25)");
        NonMemberBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NonMemberBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MakeBookingPanelLayout = new javax.swing.GroupLayout(MakeBookingPanel);
        MakeBookingPanel.setLayout(MakeBookingPanelLayout);
        MakeBookingPanelLayout.setHorizontalGroup(
            MakeBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MakeBookingPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(MakeBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(24, 24, 24)
                .addGroup(MakeBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DepartureBox, 0, 208, Short.MAX_VALUE)
                    .addComponent(DestinationBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MakeBookingPanelLayout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addGroup(MakeBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MakeBookingPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(25, 25, 25)
                        .addComponent(DayBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(MonthBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(YearBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MakeBookingPanelLayout.createSequentialGroup()
                        .addComponent(MemberBox)
                        .addGap(37, 37, 37)
                        .addComponent(NonMemberBox)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MakeBookingPanelLayout.createSequentialGroup()
                        .addComponent(ConfirmBookingButton)
                        .addGap(94, 94, 94))))
        );
        MakeBookingPanelLayout.setVerticalGroup(
            MakeBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MakeBookingPanelLayout.createSequentialGroup()
                .addGroup(MakeBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DayBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MonthBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(YearBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(MakeBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MakeBookingPanelLayout.createSequentialGroup()
                        .addComponent(DepartureBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addGroup(MakeBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DestinationBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addComponent(jLabel3))
                .addGap(26, 26, 26)
                .addGroup(MakeBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MemberBox)
                    .addComponent(NonMemberBox))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(ConfirmBookingButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout BookaTripFrameLayout = new javax.swing.GroupLayout(BookaTripFrame.getContentPane());
        BookaTripFrame.getContentPane().setLayout(BookaTripFrameLayout);
        BookaTripFrameLayout.setHorizontalGroup(
            BookaTripFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookaTripFrameLayout.createSequentialGroup()
                .addComponent(MakeBookingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        BookaTripFrameLayout.setVerticalGroup(
            BookaTripFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookaTripFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MakeBookingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 643, Short.MAX_VALUE)
        );

        EditTripFrame.setClosable(true);
        EditTripFrame.setTitle("Edit Booking");
        EditTripFrame.setEnabled(false);
        EditTripFrame.setVisible(true);

        ConfirmBookingButton1.setText("Confirm Changes");
        ConfirmBookingButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmBookingButton1ActionPerformed(evt);
            }
        });

        DepartureBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Coventry", "London", "Luton", "Milton Keynes", "Cardiff", "Northhampton", " " }));
        DepartureBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepartureBox1ActionPerformed(evt);
            }
        });

        DestinationBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "London", "Luton", "Milton Keynes", "Cardiff", "Northhampton", "Coventry" }));
        DestinationBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DestinationBox1ActionPerformed(evt);
            }
        });

        DayBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        DayBox1.setToolTipText("Day");

        MonthBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        MonthBox1.setToolTipText("Month");

        YearBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2016", "2017", "2018", "2019", "2020" }));
        YearBox1.setToolTipText("Year");

        jLabel4.setText("Date:");

        jLabel5.setText("Destination:");

        jLabel6.setText("Departure:");

        MemberBox1.setText("Member (£20)");
        MemberBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MemberBox1ActionPerformed(evt);
            }
        });

        NonMemberBox1.setSelected(true);
        NonMemberBox1.setText("Non-Member (£25)");
        NonMemberBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NonMemberBox1ActionPerformed(evt);
            }
        });

        DeleteBookingButton.setText("Delete Booking");
        DeleteBookingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBookingButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MakeBookingPanel1Layout = new javax.swing.GroupLayout(MakeBookingPanel1);
        MakeBookingPanel1.setLayout(MakeBookingPanel1Layout);
        MakeBookingPanel1Layout.setHorizontalGroup(
            MakeBookingPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MakeBookingPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(MakeBookingPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MakeBookingPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(25, 25, 25)
                        .addComponent(DayBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(MonthBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(YearBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MakeBookingPanel1Layout.createSequentialGroup()
                        .addComponent(MemberBox1)
                        .addGap(37, 37, 37)
                        .addComponent(NonMemberBox1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MakeBookingPanel1Layout.createSequentialGroup()
                        .addGroup(MakeBookingPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(24, 24, 24)
                        .addGroup(MakeBookingPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DepartureBox1, 0, 208, Short.MAX_VALUE)
                            .addComponent(DestinationBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MakeBookingPanel1Layout.createSequentialGroup()
                        .addGroup(MakeBookingPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ConfirmBookingButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DeleteBookingButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(92, 92, 92))))
        );
        MakeBookingPanel1Layout.setVerticalGroup(
            MakeBookingPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MakeBookingPanel1Layout.createSequentialGroup()
                .addGroup(MakeBookingPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DayBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MonthBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(YearBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(MakeBookingPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MakeBookingPanel1Layout.createSequentialGroup()
                        .addComponent(DepartureBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addGroup(MakeBookingPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DestinationBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addComponent(jLabel6))
                .addGap(26, 26, 26)
                .addGroup(MakeBookingPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MemberBox1)
                    .addComponent(NonMemberBox1))
                .addGap(60, 60, 60)
                .addComponent(ConfirmBookingButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 244, Short.MAX_VALUE)
                .addComponent(DeleteBookingButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout EditTripFrameLayout = new javax.swing.GroupLayout(EditTripFrame.getContentPane());
        EditTripFrame.getContentPane().setLayout(EditTripFrameLayout);
        EditTripFrameLayout.setHorizontalGroup(
            EditTripFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditTripFrameLayout.createSequentialGroup()
                .addComponent(MakeBookingPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        EditTripFrameLayout.setVerticalGroup(
            EditTripFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditTripFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MakeBookingPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        BookingInfoFrame.setClosable(true);
        BookingInfoFrame.setResizable(true);
        BookingInfoFrame.setTitle("Booking Information");
        BookingInfoFrame.setEnabled(false);
        BookingInfoFrame.setVisible(true);

        jLabel7.setText("Date:");

        jLabel8.setText("Destination:");

        jLabel9.setText("Departure:");

        jLabel10.setText("Payment:");

        jLabel11.setText("jLabel11");

        jLabel12.setText("jLabel12");

        jLabel13.setText("jLabel13");

        jLabel14.setText("jLabel14");

        javax.swing.GroupLayout MakeBookingPanel2Layout = new javax.swing.GroupLayout(MakeBookingPanel2);
        MakeBookingPanel2.setLayout(MakeBookingPanel2Layout);
        MakeBookingPanel2Layout.setHorizontalGroup(
            MakeBookingPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MakeBookingPanel2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(MakeBookingPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MakeBookingPanel2Layout.createSequentialGroup()
                        .addGroup(MakeBookingPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(MakeBookingPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(5, 5, 5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MakeBookingPanel2Layout.createSequentialGroup()
                        .addGroup(MakeBookingPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MakeBookingPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13))))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        MakeBookingPanel2Layout.setVerticalGroup(
            MakeBookingPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MakeBookingPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(MakeBookingPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(MakeBookingPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(MakeBookingPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MakeBookingPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout BookingInfoFrameLayout = new javax.swing.GroupLayout(BookingInfoFrame.getContentPane());
        BookingInfoFrame.getContentPane().setLayout(BookingInfoFrameLayout);
        BookingInfoFrameLayout.setHorizontalGroup(
            BookingInfoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookingInfoFrameLayout.createSequentialGroup()
                .addComponent(MakeBookingPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        BookingInfoFrameLayout.setVerticalGroup(
            BookingInfoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookingInfoFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MakeBookingPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        BookingReportFrame.setClosable(true);
        BookingReportFrame.setTitle("Booking Report");
        BookingReportFrame.setEnabled(false);
        BookingReportFrame.setVisible(true);

        BookingReportTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Booking Ref.", "Departure", "Destination", "Date", "Cost (£)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        BookingReportTable.setCellSelectionEnabled(true);
        jScrollPane1.setViewportView(BookingReportTable);
        BookingReportTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        DayBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        DayBox3.setToolTipText("Day");

        jLabel27.setText("Enter desired date:");

        MonthBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        MonthBox3.setToolTipText("Month");

        YearBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2016", "2017", "2018", "2019", "2020" }));
        YearBox3.setToolTipText("Year");

        WeeklyReportBtn.setText("View Weekly Report");
        WeeklyReportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WeeklyReportBtnActionPerformed(evt);
            }
        });

        MonthlyReportBtn.setText("View Monthly Report");
        MonthlyReportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MonthlyReportBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BookingReportFrameLayout = new javax.swing.GroupLayout(BookingReportFrame.getContentPane());
        BookingReportFrame.getContentPane().setLayout(BookingReportFrameLayout);
        BookingReportFrameLayout.setHorizontalGroup(
            BookingReportFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(BookingReportFrameLayout.createSequentialGroup()
                .addGroup(BookingReportFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BookingReportFrameLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel27)
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BookingReportFrameLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(WeeklyReportBtn)
                        .addGap(18, 18, 18)))
                .addGroup(BookingReportFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(BookingReportFrameLayout.createSequentialGroup()
                        .addComponent(DayBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(MonthBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(YearBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(MonthlyReportBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        BookingReportFrameLayout.setVerticalGroup(
            BookingReportFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BookingReportFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BookingReportFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DayBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(MonthBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(YearBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(BookingReportFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WeeklyReportBtn)
                    .addComponent(MonthlyReportBtn))
                .addGap(18, 30, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        RegisterMemberFrame.setClosable(true);
        RegisterMemberFrame.setTitle("Register Member");
        RegisterMemberFrame.setEnabled(false);
        RegisterMemberFrame.setVisible(true);

        ConfirmBookingButton2.setText("Confirm Registration");
        ConfirmBookingButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmBookingButton2ActionPerformed(evt);
            }
        });

        DayBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        DayBox2.setToolTipText("Day");

        MonthBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        MonthBox2.setToolTipText("Month");

        YearBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998" }));
        YearBox2.setToolTipText("Year");

        jLabel23.setText("Name:");

        jLabel24.setText("E-mail:");

        jLabel25.setText("Date of Birth:");

        jLabel26.setText("Contact Number:");

        javax.swing.GroupLayout MakeBookingPanel4Layout = new javax.swing.GroupLayout(MakeBookingPanel4);
        MakeBookingPanel4.setLayout(MakeBookingPanel4Layout);
        MakeBookingPanel4Layout.setHorizontalGroup(
            MakeBookingPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MakeBookingPanel4Layout.createSequentialGroup()
                .addGroup(MakeBookingPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MakeBookingPanel4Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(ConfirmBookingButton2))
                    .addGroup(MakeBookingPanel4Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(MakeBookingPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(28, 28, 28)
                        .addGroup(MakeBookingPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(MakeBookingPanel4Layout.createSequentialGroup()
                                .addComponent(DayBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(MonthBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(YearBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(NameTextBox)
                            .addComponent(EmailTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(MakeBookingPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel26)
                        .addGap(24, 24, 24)
                        .addComponent(ContactNumberTextBox)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        MakeBookingPanel4Layout.setVerticalGroup(
            MakeBookingPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MakeBookingPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MakeBookingPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(NameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MakeBookingPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(DayBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MonthBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(YearBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(MakeBookingPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(EmailTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MakeBookingPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(ContactNumberTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 207, Short.MAX_VALUE)
                .addComponent(ConfirmBookingButton2)
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout RegisterMemberFrameLayout = new javax.swing.GroupLayout(RegisterMemberFrame.getContentPane());
        RegisterMemberFrame.getContentPane().setLayout(RegisterMemberFrameLayout);
        RegisterMemberFrameLayout.setHorizontalGroup(
            RegisterMemberFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterMemberFrameLayout.createSequentialGroup()
                .addComponent(MakeBookingPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        RegisterMemberFrameLayout.setVerticalGroup(
            RegisterMemberFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterMemberFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MakeBookingPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EditTripFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BookingInfoFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BookaTripFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(BookingReportFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addComponent(RegisterMemberFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1180, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(BookaTripFrame, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BookingInfoFrame, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EditTripFrame, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BookingReportFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RegisterMemberFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BookATripButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookATripButtonActionPerformed
        BookaTripFrame.setVisible(true);
    }//GEN-LAST:event_BookATripButtonActionPerformed

    private void NonMemberBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NonMemberBoxActionPerformed
        MemberBox.setSelected(false);
    }//GEN-LAST:event_NonMemberBoxActionPerformed

    private void MemberBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MemberBoxActionPerformed
        NonMemberBox.setSelected(false);
    }//GEN-LAST:event_MemberBoxActionPerformed

    private void DestinationBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DestinationBoxActionPerformed

    }//GEN-LAST:event_DestinationBoxActionPerformed

    private void DepartureBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepartureBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DepartureBoxActionPerformed

    private void ConfirmBookingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmBookingButtonActionPerformed
        if(DestinationBox.getSelectedItem()==DepartureBox.getSelectedItem()){
            JOptionPane.showMessageDialog(null, "The departure and destination cannot be the same!");
        }
        else{
            try{
                double cost;
                //credentials
                String url="jdbc:derby://localhost:1527/BookingSystemDB/";
                String username ="operator";
                String password = "password";
                Connection con = DriverManager.getConnection(url, username, password);

                Statement stmt = con.createStatement();
                if(MemberBox.isSelected()){
                    cost=20.0;
                }
                else{
                    cost=25.0;
                }
                Random x = new Random();
                int bookingRef= 100000 + x.nextInt(999999);
                String Query = "INSERT INTO BOOKING(BOOKINGREF,BOOKINGDESTINATION,BOOKINGDEPARTURE,BOOKINGDATE,BOOKINGCOST) VALUES("+ bookingRef +", '"+ DestinationBox.getSelectedItem() +"', '"+ DepartureBox.getSelectedItem() +"','" + YearBox.getSelectedItem() +"-"+ MonthBox.getSelectedItem() +"-"+ DayBox.getSelectedItem() +"',"+cost+")";
                stmt.execute(Query);
                JOptionPane.showMessageDialog(null, "Booking successfully added to the database.");
                BookaTripFrame.setVisible(false);
            }
            catch(SQLException ex){
                JOptionPane.showMessageDialog(null, ex.toString());
            }

        }
    }//GEN-LAST:event_ConfirmBookingButtonActionPerformed

    private void BookingIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookingIDFieldActionPerformed

    }//GEN-LAST:event_BookingIDFieldActionPerformed

    private void BookingIDFieldInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_BookingIDFieldInputMethodTextChanged

    }//GEN-LAST:event_BookingIDFieldInputMethodTextChanged

    private void ConfirmBookingButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmBookingButton1ActionPerformed
        try{
                double cost;
                //credentials
                String url="jdbc:derby://localhost:1527/BookingSystemDB/";
                String username ="operator";
                String password = "password";
                Connection con = DriverManager.getConnection(url, username, password);

                Statement stmt = con.createStatement();
                if(MemberBox1.isSelected()){
                    cost=20.0;
                }
                else{
                    cost=25.0;
                }
                String Query = "UPDATE BOOKING SET BOOKINGDESTINATION = '"+ DestinationBox1.getSelectedItem() +"', BOOKINGDEPARTURE= '"+ DepartureBox1.getSelectedItem() +"' ,BOOKINGDATE = '"+ YearBox1.getSelectedItem() +"-"+ MonthBox1.getSelectedItem() +"-"+ DayBox1.getSelectedItem()+"' ,BOOKINGCOST = "+ cost+" WHERE BOOKINGREF = "+ BookingIDField.getText() +"";
                stmt.execute(Query);
                JOptionPane.showMessageDialog(null, "Booking successfully modified.");
            }
            catch(SQLException ex){
                JOptionPane.showMessageDialog(null, ex.toString());
            }
    }//GEN-LAST:event_ConfirmBookingButton1ActionPerformed

    private void DepartureBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepartureBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DepartureBox1ActionPerformed

    private void DestinationBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DestinationBox1ActionPerformed
        MemberBox1.setSelected(false);
    }//GEN-LAST:event_DestinationBox1ActionPerformed

    private void MemberBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MemberBox1ActionPerformed
        NonMemberBox1.setSelected(false);
    }//GEN-LAST:event_MemberBox1ActionPerformed

    private void NonMemberBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NonMemberBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NonMemberBox1ActionPerformed

    private void DeleteBookingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBookingButtonActionPerformed
        int answer = JOptionPane.showConfirmDialog(null, "are you sure you want to delete this booking?","Confirm",JOptionPane.YES_NO_OPTION);
        if (answer == JOptionPane.YES_OPTION) {
          // User clicked YES.

            if(!BookingIDField.getText().equals("")){
                try{
                //credentials
                String url="jdbc:derby://localhost:1527/BookingSystemDB/";
                String username ="operator";
                String password = "password";
                Connection con = DriverManager.getConnection(url, username, password);
                //String checkID = "DELETE FROM BOOKING WHERE BOOKINGREF = " + BookingIDField.getText()+ "";
                //Statement st = con.createStatement();
                PreparedStatement st = con.prepareStatement("DELETE FROM BOOKING WHERE BOOKINGREF = " + BookingIDField.getText()+ "");
                st.executeUpdate(); 

                JOptionPane.showMessageDialog(null, "Booking sucessfully deleted.");
                EditBookingButton.setEnabled(false);
                DeleteBookingButton.setEnabled(false);

                }
                catch(SQLException ex){
                   JOptionPane.showMessageDialog(null, ex.toString());
                }
                }
            else{
                JOptionPane.showMessageDialog(null, "Booking ID cannot be empty.");
            }
        }
    }//GEN-LAST:event_DeleteBookingButtonActionPerformed

    private void EditBookingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditBookingButtonActionPerformed
        EditTripFrame.setVisible(true);
        try{
                //credentials
                String url="jdbc:derby://localhost:1527/BookingSystemDB/";
                String username ="operator";
                String password = "password";
                Connection con = DriverManager.getConnection(url, username, password);
                Statement stmt = con.createStatement();   
                String Query = "SELECT * from BOOKING WHERE BOOKINGREF = " + BookingIDField.getText()+ "";
                stmt.execute(Query);
                ResultSet temp = stmt.getResultSet();
                temp.next();
                DestinationBox1.setSelectedItem(temp.getString("BOOKINGDESTINATION"));
                DepartureBox1.setSelectedItem(temp.getString("BOOKINGDEPARTURE"));;
                String bookingdate = new String(temp.getString("BOOKINGDATE"));
                String Year = Character.toString((bookingdate.charAt(0)))+Character.toString((bookingdate.charAt(1)))+Character.toString((bookingdate.charAt(2)))+Character.toString((bookingdate.charAt(3)));
                String Month = Character.toString((bookingdate.charAt(5)))+ Character.toString((bookingdate.charAt(6)));
                String Day = Character.toString((bookingdate.charAt(8)))+ Character.toString((bookingdate.charAt(9)));
                YearBox1.setSelectedItem(Year);
                MonthBox1.setSelectedItem(Month);
                DayBox1.setSelectedItem(Day);
                JOptionPane.showMessageDialog(null, Day);
                if((temp.getInt("BOOKINGCOST")>21)){
                    NonMemberBox1.setSelected(true);
                    MemberBox1.setSelected(false);
                }
                else{
                    MemberBox1.setSelected(true);
                    NonMemberBox1.setSelected(false);
                }
            }
            catch(SQLException ex){
                JOptionPane.showMessageDialog(null, ex.toString());
            }
    }//GEN-LAST:event_EditBookingButtonActionPerformed

    private void ViewBookingReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewBookingReportActionPerformed
        BookingReportFrame.setVisible(true);
        String url="jdbc:derby://localhost:1527/BookingSystemDB/";
        try{
            int row=0, column =0;
            ArrayList columnNames = new ArrayList();
            ArrayList data = new ArrayList();
            String username ="operator";
            String password = "password";
            Connection con = DriverManager.getConnection(url, username, password);
            String getAll = "SELECT * from BOOKING";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(getAll); 
            DefaultTableModel ReportModel=new DefaultTableModel(0, 5);
            BookingReportTable.setModel(ReportModel);
            //ResultSetMetaData md = rs.getMetaData();
            
            //BookingReportTable.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
            //BookingReportTable.setFillsViewportHeight(true);
            //JScrollPane scroll = new JScrollPane(BookingReportTable);
            /*
            scroll.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
            scroll.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);*/
            HashMap<Integer,String> code_table;
            while (rs.next()) {
                Object rowData[][] ={{" "}};
                ReportModel.addRow(rowData);
                
                column = 0;
                int BookingRef = rs.getInt("BOOKINGREF");
                BookingReportTable.setValueAt(BookingRef, row, column);
                column++;
                String Departure = rs.getString("BOOKINGDEPARTURE");
                BookingReportTable.setValueAt(Departure, row, column);
                column++;
                String Destination = rs.getString("BOOKINGDESTINATION");
                BookingReportTable.setValueAt(Destination, row, column);
                column++;
                String Date = rs.getString("BOOKINGDATE");
                BookingReportTable.setValueAt(Date, row, column);
                column++;
                String Cost = rs.getString("BOOKINGCOST");
                BookingReportTable.setValueAt(Cost, row, column);              
                row++;
            }
     
  

        }
        catch(SQLException ex){
               JOptionPane.showMessageDialog(null, ex.toString());
            }   
    }//GEN-LAST:event_ViewBookingReportActionPerformed

    private void ConfirmBookingButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmBookingButton2ActionPerformed
        if(DestinationBox.getSelectedItem()==DepartureBox.getSelectedItem()){
            JOptionPane.showMessageDialog(null, "The departure and destination cannot be the same!");
        }
        else{
            try{
                double cost;
                //credentials
                String url="jdbc:derby://localhost:1527/BookingSystemDB/";
                String username ="operator";
                String password = "password";
                Connection con = DriverManager.getConnection(url, username, password);

                Statement stmt = con.createStatement();
                Random x = new Random();
                int CustomerRef= 100000 + x.nextInt(999999);
                String Query = "INSERT INTO CUSTOMER(CUSTOMERID,CUSTOMERNAME,CUSTOMEREMAIL,CUSTOMERDATEOFBIRTH,CONTACTNUMBER) VALUES("+ CustomerRef +", '"+ NameTextBox.getText() +"', '"+ EmailTextBox.getText() +"','" + YearBox2.getSelectedItem() +"-"+ MonthBox2.getSelectedItem() +"-"+ DayBox2.getSelectedItem() +"',"+ContactNumberTextBox.getText()+")";
                stmt.execute(Query);
                JOptionPane.showMessageDialog(null, "Customer successfully added to the database.");
                BookaTripFrame.setVisible(false);
            }
            catch(SQLException ex){
                JOptionPane.showMessageDialog(null, ex.toString());
            }

        }
    }//GEN-LAST:event_ConfirmBookingButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        RegisterMemberFrame.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void WeeklyReportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WeeklyReportBtnActionPerformed
        String url="jdbc:derby://localhost:1527/BookingSystemDB/";
        try{
            int row=0, column =0;
            String username ="operator";
            String password = "password";
            Connection con = DriverManager.getConnection(url, username, password);
            int temp = DayBox3.getSelectedIndex();
            String getAll = "SELECT * from BOOKING WHERE(BOOKINGDATE>='"+YearBox3.getSelectedItem() +"-"+ MonthBox3.getSelectedItem() +"-"+ DayBox3.getSelectedItem() +"' AND BOOKINGDATE<='"+YearBox3.getSelectedItem() +"-"+ MonthBox3.getSelectedItem() +"-"+ DayBox3.getItemAt(temp+6) +"')" ;
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(getAll); 
            DefaultTableModel ReportModel=new DefaultTableModel(0, 5);
            BookingReportTable.setModel(ReportModel);
            while (rs.next()) {
                Object rowData[][] ={{" "}};
                ReportModel.addRow(rowData);
                
                column = 0;
                int BookingRef = rs.getInt("BOOKINGREF");
                BookingReportTable.setValueAt(BookingRef, row, column);
                column++;
                String Departure = rs.getString("BOOKINGDEPARTURE");
                BookingReportTable.setValueAt(Departure, row, column);
                column++;
                String Destination = rs.getString("BOOKINGDESTINATION");
                BookingReportTable.setValueAt(Destination, row, column);
                column++;
                String Date = rs.getString("BOOKINGDATE");
                BookingReportTable.setValueAt(Date, row, column);
                column++;
                String Cost = rs.getString("BOOKINGCOST");
                BookingReportTable.setValueAt(Cost, row, column);              
                row++;
            }
            JOptionPane.showMessageDialog(null,"Report successfully updated!");
  

        }
        catch(SQLException ex){
               JOptionPane.showMessageDialog(null, ex.toString());
            }   
    }//GEN-LAST:event_WeeklyReportBtnActionPerformed

    private void MonthlyReportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MonthlyReportBtnActionPerformed
        String url="jdbc:derby://localhost:1527/BookingSystemDB/";
        try{
            int row=0, column =0;
            String username ="operator";
            String password = "password";
            Connection con = DriverManager.getConnection(url, username, password);
            String getAll = "SELECT * from BOOKING WHERE(BOOKINGDATE>='"+YearBox3.getSelectedItem() +"-"+ MonthBox3.getSelectedItem() +"-"+ "01" +"' AND BOOKINGDATE<='"+YearBox3.getSelectedItem() +"-"+ MonthBox3.getSelectedItem() +"-"+ "31" +"')" ;
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(getAll); 
            DefaultTableModel ReportModel=new DefaultTableModel(0, 5);
            BookingReportTable.setModel(ReportModel);
            while (rs.next()) {
                Object rowData[][] ={{" "}};
                ReportModel.addRow(rowData);
                
                column = 0;
                int BookingRef = rs.getInt("BOOKINGREF");
                BookingReportTable.setValueAt(BookingRef, row, column);
                column++;
                String Departure = rs.getString("BOOKINGDEPARTURE");
                BookingReportTable.setValueAt(Departure, row, column);
                column++;
                String Destination = rs.getString("BOOKINGDESTINATION");
                BookingReportTable.setValueAt(Destination, row, column);
                column++;
                String Date = rs.getString("BOOKINGDATE");
                BookingReportTable.setValueAt(Date, row, column);
                column++;
                String Cost = rs.getString("BOOKINGCOST");
                BookingReportTable.setValueAt(Cost, row, column);              
                row++;
            }
            JOptionPane.showMessageDialog(null,"Report successfully updated!");
  

        }
        catch(SQLException ex){
               JOptionPane.showMessageDialog(null, ex.toString());
            }   
    }//GEN-LAST:event_MonthlyReportBtnActionPerformed

    
        private void VerifyBookingButtonActionPerformed(java.awt.event.ActionEvent evt) {
        if(!BookingIDField.getText().equals("")){
            try{
            //credentials
            String url="jdbc:derby://localhost:1527/BookingSystemDB/";
            String username ="operator";
            String password = "password";
            Connection con = DriverManager.getConnection(url, username, password);
            String checkID = "SELECT * from BOOKING WHERE BOOKINGREF = " + BookingIDField.getText()+ "";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(checkID); 

            if(rs.next()) {//booking exists
                JOptionPane.showMessageDialog(null, "Booking exists.");
                EditBookingButton.setEnabled(true);
                DeleteBookingButton.setEnabled(true);
            }
            else{//booking does not exist
                JOptionPane.showMessageDialog(null, "Booking does not exist.");
                EditBookingButton.setEnabled(false);
                DeleteBookingButton.setEnabled(false);
            }
            
            jLabel11.setText(rs.getString("BOOKINGDATE"));
            jLabel12.setText(rs.getString("BOOKINGDEPARTURE"));
            jLabel13.setText(rs.getString("BOOKINGDESTINATION"));
            jLabel14.setText("£"+rs.getString("BOOKINGCOST"));
            
            //display booking information
            BookingInfoFrame.setVisible(true);
            
            }
            catch(SQLException ex){
               JOptionPane.showMessageDialog(null, ex.toString());
            }
            }
        else{
            JOptionPane.showMessageDialog(null, "Booking ID cannot be empty.");
        }
    }  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OperatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OperatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OperatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OperatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OperatorGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BookATripButton;
    private javax.swing.JInternalFrame BookaTripFrame;
    private javax.swing.JTextField BookingIDField;
    private javax.swing.JInternalFrame BookingInfoFrame;
    private javax.swing.JInternalFrame BookingInfoFrame1;
    private javax.swing.JInternalFrame BookingReportFrame;
    private javax.swing.JTable BookingReportTable;
    private javax.swing.JButton ConfirmBookingButton;
    private javax.swing.JButton ConfirmBookingButton1;
    private javax.swing.JButton ConfirmBookingButton2;
    private javax.swing.JTextField ContactNumberTextBox;
    private javax.swing.JComboBox<String> DayBox;
    private javax.swing.JComboBox<String> DayBox1;
    private javax.swing.JComboBox<String> DayBox2;
    private javax.swing.JComboBox<String> DayBox3;
    private javax.swing.JButton DeleteBookingButton;
    private javax.swing.JComboBox<String> DepartureBox;
    private javax.swing.JComboBox<String> DepartureBox1;
    private javax.swing.JComboBox<String> DestinationBox;
    private javax.swing.JComboBox<String> DestinationBox1;
    private javax.swing.JButton EditBookingButton;
    private javax.swing.JInternalFrame EditTripFrame;
    private javax.swing.JTextField EmailTextBox;
    private javax.swing.JPanel MakeBookingPanel;
    private javax.swing.JPanel MakeBookingPanel1;
    private javax.swing.JPanel MakeBookingPanel2;
    private javax.swing.JPanel MakeBookingPanel3;
    private javax.swing.JPanel MakeBookingPanel4;
    private javax.swing.JCheckBox MemberBox;
    private javax.swing.JCheckBox MemberBox1;
    private javax.swing.JComboBox<String> MonthBox;
    private javax.swing.JComboBox<String> MonthBox1;
    private javax.swing.JComboBox<String> MonthBox2;
    private javax.swing.JComboBox<String> MonthBox3;
    private javax.swing.JButton MonthlyReportBtn;
    private javax.swing.JTextField NameTextBox;
    private javax.swing.JCheckBox NonMemberBox;
    private javax.swing.JCheckBox NonMemberBox1;
    private javax.swing.JInternalFrame RegisterMemberFrame;
    private javax.swing.JButton VerifyBookingButton;
    private javax.swing.JButton ViewBookingReport;
    private javax.swing.JButton WeeklyReportBtn;
    private javax.swing.JComboBox<String> YearBox;
    private javax.swing.JComboBox<String> YearBox1;
    private javax.swing.JComboBox<String> YearBox2;
    private javax.swing.JComboBox<String> YearBox3;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
